version: '3'

services:

  app:
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    env_file: ./containers/app/.env
    volumes:
      - .:/opt/app
    links:
      - database
      - redis
    ports:
      - "5555:5555"
    tty: true
    stdin_open: true
    command: /bin/sh -c 'rm -f /opt/app/tmp/pids/server.pid && bundle exec rake tmp:clear && bundle exec rails s -p 5555 -b 0.0.0.0'
    networks:
      - default
      - ark

  database:
    image: postgres:10.1
    environment:
      POSTGRES_PASSWORD: cars_writer_pw
      POSTGRES_USER: cars_writer
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - default

  redis:
    image: redis:3.2.8-alpine
    ports:
      - "6399:6379"
    networks:
      - default
